### ISSUE TITLE
Environment.Exit()

### ISSUE THREAD

**Issue by l0ss** [nheiniger/SnaffPoint#1]
I haven't had a chance to take this for a spin yet but had a quick look at the code - can I recommend removing Environment.Exit() wherever possible? Lots of in-memory execution tools will take down their parent beacon when they hit Environment.Exit().

**Comment by nheiniger** [comment]
Resolved with commit https://github.com/nheiniger/SnaffPoint/commit/853f99b93f1bbb4bf7921caaa37c4dbb4e6cac28
