### ISSUE TITLE
Request failed with exception

### ISSUE THREAD

**Issue by Namae-no-nai-Kaibutsu** [nheiniger/SnaffPoint#7]
Queries are failing with the error 'The maximum nametable character count quota (16384) has been exceeded while reading XML data. The nametable is a data structure used to store strings encountered during XML processing - long XML documents with non-repeating element names, attribute names and attribute values may trigger this quota. This quota may be increased by changing the MaxNameTableCharCount property on the XmlDictionaryReaderQuotas object used when creating the XML reader.'

**Comment by nheiniger** [comment]
Do you have a way to reproduce the issue? When does it happen?

I don't have access to a test environment at the moment so it might be hard for me to debug that. But I would be happy to approve a PR.

**Comment by Namae-no-nai-Kaibutsu** [comment]
Hey , I have simply followed the steps as is .

> GetBearerToken to generate the token 
> use the token and then try to query . 

For some weird reason it is working now.  I am not sure why it is working . I just wrapped the Token with Double quotes
